[build]
  publish = "dist/"
  command = "yarn build"
  #functions = "functions/"

# Production context: all deploys from the Production branch set in your site’s
# deploy contexts will inherit these settings.
[context.production]
  publish = "dist/"
  command = "yarn build"
  environment = { NODE_VERSION = "14.15" }
